name: plant_care_app
description: Приложение для ухода за растениями
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  timezone: ^0.11.0
  image_picker: ^1.0.4
  http: ^1.1.0
  provider: ^6.1.2
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/data/care_tips.json
    - assets/images/monstera.jpg
    - assets/images/ficus.jpg
    - assets/images/zamioculcas.jpg
    - assets/images/sansevieria.jpg
    - assets/images/chlorophytum.jpg
    - assets/images/crassula.jpg
    - assets/images/spathiphyllum.jpg
    - assets/images/aloe.jpg
    - assets/images/anthurium.jpg
    - assets/images/geranium.jpg
    - assets/images/begonia.jpg
    - assets/images/dracaena.jpg
    - assets/images/schefflera.jpg
    - assets/images/violet.jpg
    - assets/images/cactus.jpg
    - assets/images/ivy.jpg